import type { PriceCategory } from "@/features/pricing/types";

export const pricingCategories: PriceCategory[] = [
  {
    id: "nails",
    title: "Nails",
    summary: "Gel, shellac, refills, polish changes, and hand care.",
    accent: "bg-white/80",
    items: [
      { name: "Bio Gel", price: "$70" },
      { name: "Gel X", price: "$80" },
      { name: "Manicure", price: "$40" },
      { name: "Shellac manicure", price: "$45" },
      { name: "Paraffin add-on", price: "$20" },
      { name: "Bio Gel refill", price: "$55" },
      { name: "French manicure", price: "$40" },
      { name: "French shellac manicure", price: "$45" },
      { name: "Polish change", price: "$30" },
      { name: "Full set nails", price: "$70" },
      { name: "Gel overlay", price: "$50" },
      { name: "Gel removal", price: "$30" },
      { name: "Manicure & pedicure", price: "$80" },
      { name: "Nail clip and file", price: "$55" },
      { name: "Nail refill", price: "$55" },
      { name: "Princess manicure (kids)", price: "$25" },
      { name: "Princess manicure & pedicure", price: "$50" },
      { name: "Shellac manicure & pedicure", price: "$85" },
      { name: "Shellac polish change", price: "$35" },
    ],
  },
  {
    id: "massages",
    title: "Massages",
    summary: "Focused body work and relaxation services brought home.",
    accent: "bg-white/80",
    items: [
      { name: "30 min Back", price: "$50" },
      { name: "45 min Thai foot massage", price: "$70" },
      { name: "60 min Body massage", price: "$95" },
      { name: "Body scrub", price: "$50" },
      { name: "Shoulder massage (20 mins)", price: "$40" },
      { name: "Swedish deep tissue massage", price: "$95" },
      { name: "Deep tissue massage with cupping", price: "$190" },
    ],
  },
  {
    id: "feet",
    title: "Feet",
    summary: "Pedicures, foot care, polish, and comfort-focused add-ons.",
    accent: "bg-white/80",
    items: [
      { name: "Pedicure starting at", price: "$50" },
      { name: "Paraffin add-on", price: "$20" },
      { name: "French Pedicure", price: "$55" },
      { name: "Polish Change", price: "$25" },
      { name: "Princess Pedicure (kids)", price: "$40" },
      { name: "Shellac pedicure", price: "$55" },
      { name: "Nail clip & file", price: "$20" },
      { name: "Medical Pedicure", price: "$75" },
      { name: "Jelly pedicure", price: "$75" },
      { name: "Signature spa manicure", price: "$65" },
    ],
  },
  {
    id: "waxing",
    title: "Waxing",
    summary: "Face and body waxing options for at-home appointments.",
    accent: "bg-white/80",
    items: [
      { name: "Eyebrows & shaping", price: "$20" },
      { name: "Chin & upper lip", price: "$20" },
      { name: "Half arm", price: "$25" },
      { name: "Half leg", price: "$35" },
      { name: "Full leg & bikini", price: "$80" },
      { name: "Bikini", price: "$36" },
      { name: "Upper lip", price: "$10" },
      { name: "Full face", price: "$35" },
      { name: "Full arm", price: "$40" },
      { name: "Full leg", price: "$55" },
      { name: "Under arm", price: "$30" },
      { name: "Brazilian", price: "$75" },
      { name: "Back", price: "$35" },
      { name: "Full body (women only)", price: "$175" },
      { name: "Full face", price: "$35" },
    ],
  },
  {
    id: "lashes",
    title: "Lashes",
    summary: "Classic, hybrid, volume, glam, and mega volume sets.",
    accent: "bg-white/80",
    items: [
      { name: "Classic Set", price: "$135" },
      { name: "Refill Classic", price: "$80" },
      { name: "Lash set Hybrid", price: "$155" },
      { name: "Refill Hybrid", price: "$90" },
      { name: "Lash Set Volume", price: "$160" },
      { name: "Refill Volume", price: "$100" },
      { name: "Lash Set Glam Volume", price: "$170" },
      { name: "Refill Glam Volume", price: "$110" },
      { name: "Lash Set Mega Volume", price: "$225" },
      { name: "Refill Mega Volume", price: "$140" },
    ],
  },
];

// Offline fallback for the Facials section, mirroring the facials category in
// db/seeds.rb (the source of truth). The live /services page renders facials
// from the API; this only shows when the API is unreachable.
export const FACIAL_SERVICES: PriceCategory = {
  id: "facials",
  title: "Facials",
  summary:
    "Facials, peels, back treatments, and facial, scalp, and lymphatic massage with Rim.",
  accent: "bg-[#eef1ec]",
  items: [
    {
      name: "Express facial (women only)",
      duration: "45 min",
      price: "$95",
      description: "A quick, refreshing facial - cleanse, exfoliation, mask, and hydration to leave skin glowing.",
    },
    {
      name: "Deep facial (women only)",
      duration: "75 min",
      price: "$135",
      description: "A thorough deep-cleansing facial with extractions, exfoliation, a treatment mask, and massage.",
    },
    {
      name: "Microdermabrasion add on (women only)",
      duration: "30 min",
      price: "$50",
      description: "A resurfacing add-on that gently buffs away dull, dead skin. Added to any facial.",
    },
    {
      name: "Problem skin facial (women only)",
      duration: "90 min",
      price: "$160",
      description: "A targeted facial for congested, acne-prone, or reactive skin.",
    },
    {
      name: "Full Back facial (women only)",
      duration: "60 min",
      price: "$120",
      description: "Cleanses, exfoliates, and clears congestion across the full back.",
    },
    {
      name: "Half Back facial (women only)",
      duration: "40 min",
      price: "$65",
      description: "A focused facial for the upper or lower back.",
    },
    {
      name: "Face chemical peel (women only)",
      duration: "45 min",
      price: "$150",
      description: "A professional chemical peel to improve tone, texture, and clarity.",
    },
    {
      name: "Underarm chemical peel (women only)",
      duration: "30 min",
      price: "$150",
      description: "A brightening peel that targets darkness and uneven tone.",
    },
    {
      name: "Upper back chemical peel (women only)",
      duration: "60 min",
      price: "$200",
      description: "A deeper peel for the upper back to clear congestion and improve tone.",
    },
    {
      name: "Facial massage add on (women only)",
      duration: "15 min",
      price: "$40",
      description: "A relaxing facial massage added to any treatment.",
    },
    {
      name: "Head & scalp massage (women only)",
      duration: "30 min",
      price: "$40",
      description: "A soothing head and scalp massage that releases tension.",
    },
    {
      name: "Lymphatic drainage massage (full body, 1 hour, women only)",
      duration: "60 min",
      price: "$140",
      description: "A gentle, full-body lymphatic drainage massage.",
    },
  ],
};
